### PR TITLE
Unprivileged user should be called `ffig`

### PR DESCRIPTION
**Pull request by ajbennieston**
Change from `c-api-user` to `ffig`.

### CODE REVIEW

**Comment by petr-tik** [comment]
maybe call it ffig_user? 

I find it way too confusing to have ffig user chowning a ffig repo, which has a ffig dir inside with FFIG.py file

**Comment by ajbennieston** [comment]
I don't find it particularly confusing. On the other hand, the notation `foo_user` for user accounts is some kind of unnecessary Hungarian notation for usernames.

I've no strong preference, if you'd like to change it.

**Comment by petr-tik** [comment]
@jbcoe please cast the deciding vote

**Comment by jbcoe** [comment]
It's ffigs all the way down.

Sorry this slipped off my radar for so long! Feel free to ping me another time.

**Review by jbcoe — APPROVED** [review]

**Pull request merged**
